### ISSUE TITLE
All recent reggie builds are failing on tests

### ISSUE THREAD

**Issue by cvcotton** [Voteshield/reggie#69]
These failures just started today, even on branches with very trivial changes, e.g. this single line fix PR: https://github.com/Voteshield/reggie/pull/68

Looks like this:
![Screen Shot 2021-07-07 at 1 38 04 PM](https://user-images.githubusercontent.com/2606790/124804718-9c5da200-df28-11eb-92a7-dcd8ed1f1841.png)

**Comment by zzolo** [comment]
It looks like `ParserError` has been moved?
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.errors.ParserError.html

Though I don't understand what changed.

**Comment by nicholastulach** [comment]
> And I'm not sure why it would be different between Python versions.

Perhaps newer versions of Pandas aren't compatible with older versions of python? That seems unlikely, but possible…?
